### GENERAL SETTINGS ###

# Site settings
title: Centre for Hydrology | Modeling and prediction
description: "We seek to improve understanding and predictions of hydrological processes at scales from hillslopes to continents"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl:  "" #important: start with /
url: "https://martynpclark.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#417630" #"#00b3fe" #"#F70031"
  primary_rgb: "65,118,48" #"0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#719500" #e8e3d3" #"#85754d" #"#384452" #"#33004D"
  link: "#ffffff" #"#428bca"
  link_hover: "#85754d"#"#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#ffffff" #d9d9d9" #"#bfc9d3"
  text: "#444444"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
online:
  - title: github
    url: https://github.com/martynpclark
  # - title: facebook
  #   url: https://github.com/UW-Hydro
  # - title: twitter
  #   url:
  # - title: instagram
  #   url:
  # - title: tumblr
  #   url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Coldwater Laboratory
    - 1151 Sidney Street, unit 116
    - Canmore, Alberta, T1W 3G1, CANADA

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Project information. Shown on Home and About pages.
# projects:
#   - name: RASM
#     img: client01.png
#   - name: Drought Monitor
#     img: client02.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We seek to improve understanding and predictions of hydrological processes at scales from hillslopes to continents"
